sudo: false
language: cpp
compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      dist: trusty

before_install:
  - sudo apt-get -y install python3 python3-pip
  - pip3 install --user meson==0.43.0

script:
  - meson builddir
  - ninja -C builddir
  - ninja -C builddir test
