sudo: false
language: cpp
compiler:
  - gcc
  - clang
os: linux
dist: xenial

before_install:
  - sudo apt-get -y install python3 python3-setuptools python3-pip ninja-build
  - pip3 install --user meson==0.50.0

script:
  - meson builddir
  - ninja -C builddir
  - ninja -C builddir test
